### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by aHollowMind** [ghostinthecamera/IGCS-GITC#12]
I launch the game as admin, wait for the game to load. Launch the exe as admin, inject the dll, get a pop up saying it was successful. However, notification pops up in the game window, and ctrl + ins does not open a menu.

Not sure if I am doing something wrong, or if this was broken by a recent game update.

**Comment by ghostinthecamera** [comment]
It should still inject, even if there was an update. 
I'll need more information to help - what does the pop up say? what does the CMD window that starts with the tools say?

**Comment by aHollowMind** [comment]
Ace Combat 7. After following the steps to inject a pop up comes up that says "Injection Succeed. Enjoy!" but there is not indication that it succeed in the game window, and ctrl + ins does not open a menu.

**Comment by ghostinthecamera** [comment]
Are you using the latest version of the tools?

**Comment by aHollowMind** [comment]
Yes. I am using 1.4
I re downloaded before replying to your comment just to make sure the issue had not somehow corrected since I made the original post.

**Comment by ghostinthecamera** [comment]
Hmm - i can't replicate the issue - I just downloaded the game and tried v1.4. Seems to be working fine for me (See screenshot) aside from the HUD toggle which broke due to the update.

![ACE COMBAT 7  SKIES UNKNOWN Screenshot 2021 03 21 - 16 54 57 20](https://user-images.githubusercontent.com/48456322/111913476-324aeb00-8a66-11eb-9096-0b8220ac5064.png)

Perhaps try the Universal Unreal Unlocker (UUU) by Frans Bouma (you can find it here: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm). It should work with AC7 minus a few features

Please don't rehost the UUU on any other site
