### ISSUE TITLE
IGCS-GITC not working with Mechwarrior 5 DLC

### ISSUE THREAD

**Issue by Damphyre** [ghostinthecamera/IGCS-GITC#17]
Hi,

So the injector and everything seems to be working fine and I get a small icon in the top left of the screen showing it is working. However when I press insert to go to camera mode or delete to remove HUD etc non of that is doing anything. I tried rebind keys to different buttons but still not working.

Cheers

Damphrye

**Comment by Damphyre** [comment]
![image](https://user-images.githubusercontent.com/85460284/120940228-280ac580-c714-11eb-9f5b-924d3c9e434f.png)

**Comment by ghostinthecamera** [comment]
Hi there - this is probably because the game has been updated and so the tools are not compatible anymore. I don't have the game installed (so I can't check) and not sure if I will play the game again i'm afraid so it is unlikely this will get fixed.

**Comment by ghostinthecamera** [comment]
I've just checked the Universal Unreal Unlocker works with MW5 now - you can find it here: https://framedsc.github.io/GeneralGuides/universal_ue4_consoleunlocker.htm

As noted on that page, please do not host or redistribute the UUU in any way other than through that link.

It works in the same way as my tools except the hot keys are slightly different (PG DN will pause the game rather than Num 0)

**Comment by Damphyre** [comment]
Ah you're a legend thanks a ton for that mate! Should check it out though the DLC is pretty interesting for certain anyway.
