### ISSUE TITLE
The Free Camera for Ace Combat 7 crashes in Windows 7

### ISSUE THREAD

**Issue by WZNGT** [ghostinthecamera/IGCS-GITC#8]
When I run Ace Combat 7 of 1.2.2.5 version (The update with Anchorhead Raid) with GITC_AC7_Tools_v1.23, an error "Failed to create directX device and swapchain" will be shown, the mod still runs but no overlay is shown. It works ok with "Ins" command to enable, but then if "Numpad 0" is pressed the game crashes (pressing "." also crashes the game).

The website of Universal Unreal Engine 4 Console Unlocker suggest using Extreme Injector since "Some people on Windows 7 have reported issues with the IGCSInjector", I tried that but same thing happened. It it possible to get a fix?

**Comment by ghostinthecamera** [comment]
There are 2 issues here:
1) Failure to create DirectX device and Swapchain - I cannot replicate this error and therefore have no idea what is causing it. The tools are provided as-is without support and if I cannot replicate the issue there is no way a fix can be developed.
2) Gaming crashing - various game updates have broken certain features in the tools. The tools require updating to the latest version of the game - if I have time to do this I will, otherwise, sorry. You can change the default behaviour in the overlay so that Numpad 0 doesn't crash the game.

**Comment by WZNGT** [comment]
Hmm... there was no overlay in my case, and Num0 is for pause the game which is quite important, so it's basically unusable at the moment.

RythusOmega mentioned this set to be added into IGCSInjector.ini file to make it work in the current version, but the crashing still occurred on my end.
[CameraSettings]
invertY=False
allowCameraMovementWhenMenuIsUp=False
hudandtimestop=False
fastMovementMultiplier=50.000000
slowMovementMultiplier=0.040000
movementUpMultiplier=0.700000
movementSpeed=0.700000
rotationSpeed=0.010000
fovChangeSpeed=0.200000

**Comment by ghostinthecamera** [comment]
The "hudandtimestop"=false should prevent crashing (as the HUD toggle is what is broken). However, as I said, I cannot replicate the failure to create device error (and have never personally experienced it). You're options are to roll back to an older version of the game if you can't disable that function - sorry.

**Comment by WZNGT** [comment]
It works fine without any crash after the update, thanks!
BTW... will the camera work in multiplayer? I have tried to take a shot with an AI aircraft, but since they just fly around like headless bugs it's too hard to get a nice shot (and they don't have SP weapons). So I am now thinking about fly with a friend in MP for the screenshot, but not sure if it's praticle.

**Comment by ghostinthecamera** [comment]
It will work but anti cheat measures often detect the tools (and since they can't tell what the tools are doing only that they are injecting their own DLL and modifying game memory) you will be flagged for cheating. I recommend not using the tools in multiplayer as there is a risk of ban/other action.

**Comment by WZNGT** [comment]
Right......... maybe I will try to take a shot really fast and cut the internet connection so the results won't be saved for anti-cheat to verify.
Just one more thing, do you have any idea about how to remove the blue overlay on HUD from EA-18G's ESM support in SP Mission 01? Had asked a couple who were into GFX modification but didn't got much info.

**Comment by WZNGT** [comment]
Right...... maybe I can find a friend and just take the shot real quick, then just cut the internet connection on both ends so there's no result for anti-cheat to verify. Hopefully it works like that, thank you for the tool nonetheless.
