### ISSUE TITLE
AC7: Save Corruption upon using tool.

### ISSUE THREAD

**Issue by kirbyeggs** [ghostinthecamera/IGCS-GITC#9]
For Ace Combat 7
So my save gets corrupted every time I use the tool. I need to actually start the camera for it to get corrupted, just injecting the dll won't do anything. I am not sure if anyone has had this issue or if it's something specific on my end. The tool works fine and there are no issues, just the game giving me a corruption error on next boot.

**Comment by ghostinthecamera** [comment]
Hi there - i've never experienced this error or had any reports. 

If you're using the tool during multiplayer (which is NOT recommended) it is possible the anti-cheat functionality of the game is detected the injected tools as a cheat.

Otherwise, have had no issues using it in single player - sorry.

**Comment by kirbyeggs** [comment]
So I think the issue was that I had an older version of the camera tool(1.23) in the file directory and didn't clean it out properly, either that or using the mod manager for skins. I deleted all the extra stuff and using the camera tool 1.30, have no issues so far. Either that or the game itself is to blame and the save just got corrupted because that seems to be an issue with some people.
